variable "ecx_client_id" {}
variable "ecx_client_secret" {}
variable "type" {}
variable "metro_code" {}
variable "emails" {}
variable "purchase_order_number" {}
variable "code" {}
variable "project_id" {}
variable "account_number" {}
variable "metro_code_sv" {}
variable "metro_code_DA" {}
variable "IPWAN_Name" {}
